name: jzero-ci

on:
  push:
    branches:
  pull_request:

jobs:
  golangci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v6
        with:
          go-version: '1.24.3'

      - uses: actions/checkout@v5
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest
          working-directory: ${{ matrix.workdir }}
          skip-go-installation: true
          skip-pkg-cache: true

      - name: run test case
        run: |
          go test ./...